title: Nicroxio
description: "My Personal Blog For Projects"
author:
  name: "Nicroxio"
  email: "someone@somewebsite.somedomain"
  url: "Nicroxio.co.uk"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner: "Nicroxio"
year: "2020"
